services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: alhikmah_api_dev
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: alhikmah_db

  db:
    image: postgres:15
    container_name: alhikmah_db_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alhikmah_db
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
