services:
  app:
    build:
      context: .
      target: dev
    container_name: alhikmah_api_dev
    volumes:
      - .:/app
      - /app/tmp
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrate
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: alhikmah_db_dev
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  migrate:
    image: migrate/migrate
    container_name: alhikmah_migrate
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "sleep 5 &&
      migrate
      -path /migrations
      -database postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      up"
    restart: on-failure

volumes:
  db_data:
