// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/dwikikf/alhikmah-api/internal/handler"
	"github.com/dwikikf/alhikmah-api/internal/infrastucture/database"
	"github.com/dwikikf/alhikmah-api/internal/infrastucture/repository"
	"github.com/dwikikf/alhikmah-api/internal/usecase"
	"github.com/dwikikf/alhikmah-api/pkg/validator"
)

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	pool, err := database.Connect()
	if err != nil {
		return nil, err
	}
	classRepositoryImpl := repository.NewClassRepository(pool)
	studentRepositoryImpl := repository.NewStudentRepository(pool)
	unitOfWorkImpl := repository.NewUnitOfWork(pool)
	studentUsecaseImpl := usecase.NewStudentUseCaseImpl(classRepositoryImpl, studentRepositoryImpl, unitOfWorkImpl)
	customValidator := validator.NewValidator()
	studentHandler := handler.NewStudentHandler(studentUsecaseImpl, customValidator)
	classUsecaseImpl := usecase.NewClassUseCaseImpl(classRepositoryImpl, unitOfWorkImpl)
	classHandler := handler.NewClassHandler(classUsecaseImpl, customValidator)
	attendanceRepositoryImpl := repository.NewAttendanceRepository(pool)
	attendanceUsecaseImpl := usecase.NewAttendanceUseCaseImpl(attendanceRepositoryImpl, unitOfWorkImpl)
	attendanceHandler := handler.NewAttendanceHandler(attendanceUsecaseImpl, customValidator)
	handlers := &Handlers{
		Student:    studentHandler,
		Class:      classHandler,
		Attendance: attendanceHandler,
	}
	app := &App{
		Handlers: handlers,
	}
	return app, nil
}
